name: I'm using VirtualBox 6.1.26/6.1.28 OR I upgraded to MacOS 12/Monterey
description: Using VirtualBox and getting site timeouts? hostonly network adapter errors? Recently upgraded to MacOS 12?
labels: [ 'type:support' ]
body:
  - type: markdown
    attributes:
      value: |
      ## MacOS 12 Monterey

      *Do not upgrade to Monterey.*

      There are no known working versions of VirtualBox for MacOS 12, do not upgrade. ***VirtualBox intend to fix this in v6.1.29***.

      Until VirtualBox 6.1.29 is officially released, do not upgrade past MacOS 11 Big Sur. Test release builds are not guaranteed to work.

      The fastest way to restore VirtualBox is to downgrade back to MacOS 11 Big Sur, and use v6.1.24.

      ## VirtualBox 6.1.26 and 6.1.28

      These versions of VirtualBox are known to have networking problems on Linux/Windows/MacOS, not everybody encounters these problems though.

      VirtualBox 6.1.24 works though, stick to 6.1.24 until we can confirm if 6.1.29 fixes the problems.

      ## But My New M1 Mac Only Support MacOS 12!

      Use Parallels, new Macs don't support VirtualBox.

