# This is a basic workflow to help you get started with Actions

name: VVV Provisioning

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop, stable ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  on-stable:
    name: Stable Reprovision
    # The type of runner that the job will run on
    runs-on: macos-10.15

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: stable

      - name: vagrant up (stable)
        run: vagrant up

      - uses: actions/checkout@v2

      - name: vagrant up (current branch)
        run: vagrant up --provision

      - name: Prepare Output
        if: ${{ always() }}
        run: |
          sudo cp -rf "$GITHUB_WORKSPACE/log" "/vvv-logs"
          MYUID=$(id -u -n)
          MYGID=$(id -g -n)
          sudo chown -R $MYUID:$MYGID "/vvv-logs"

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: logs
          path: "/vvv-logs"

  on-develop:
    name: Develop Reprovision
    # The type of runner that the job will run on
    runs-on: macos-10.15

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: develop

      - name: vagrant up (develop)
        run: vagrant up

      - uses: actions/checkout@v2

      - name: vagrant up (current branch)
        run: vagrant up --provision

      - name: Prepare Output
        if: ${{ always() }}
        run: |
          sudo cp -rf "$GITHUB_WORKSPACE/log" "/vvv-logs"
          MYUID=$(id -u -n)
          MYGID=$(id -g -n)
          sudo chown -R $MYUID:$MYGID "/vvv-logs"

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: logs
          path: "/vvv-logs"

  on-clean:
    name: Clean Provision
    # The type of runner that the job will run on
    runs-on: macos-10.15

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: vagrant up (current branch)
        run: vagrant up

      - name: Prepare Output
        if: ${{ always() }}
        run: |
          sudo cp -rf "$GITHUB_WORKSPACE/log" "/vvv-logs"
          MYUID=$(id -u -n)
          MYGID=$(id -g -n)
          sudo chown -R $MYUID:$MYGID "/vvv-logs"

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: logs
          path: "/vvv-logs"
